import { useEffect, useState } from "react";
import { useParams, Navigate } from "react-router-dom";
import { supabase } from "@/lib/supabaseClient";
import { useAuth } from "@/contexts/SupabaseAuthContext";
import jsPDF from "jspdf";

export default function ResumeReviewExport() {
  const { id } = useParams();
  const { user, isPro, loading: authLoading } = useAuth();

  const [review, setReview] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!user) return;

    let active = true;

    const loadReview = async () => {
      const { data } = await supabase
        .from("resume_reviews")
        .select("created_at, target_role, results")
        .eq("id", id)
        .eq("user_id", user.id)
        .single();

      if (active) {
        setReview(data || null);
        setLoading(false);
      }
    };

    loadReview();

    return () => {
      active = false;
    };
  }, [id, user]);

  if (authLoading) {
    return <div className="text-gray-500">Checking access…</div>;
  }

  if (!isPro) {
    return <Navigate to="/dashboard/upgrade" replace />;
  }

  if (loading || !review) {
    return <div className="text-gray-500">Loading review…</div>;
  }

  const handleExport = () => {
    const doc = new jsPDF();
    let y = 20;
    const lineHeight = 7;
    const pageHeight = doc.internal.pageSize.height;

    const ensureSpace = (lines = 1) => {
      if (y + lines * lineHeight > pageHeight - 20) {
        doc.addPage();
        y = 20;
      }
    };

    const sectionTitle = (text) => {
      ensureSpace(2);
      doc.setFontSize(12);
      doc.setFont(undefined, "bold");
      doc.text(text, 14, y);
      y += lineHeight;
      doc.setFont(undefined, "normal");
    };

    const paragraph = (text) => {
      const lines = doc.splitTextToSize(text, 180);
      ensureSpace(lines.length + 1);
      doc.text(lines, 14, y);
      y += lines.length * lineHeight + lineHeight / 2;
    };

    const bullets = (items) => {
      items.forEach((item) => {
        const lines = doc.splitTextToSize(`• ${item}`, 175);
        ensureSpace(lines.length);
        doc.text(lines, 18, y);
        y += lines.length * lineHeight;
      });
      y += lineHeight / 2;
    };

    // ─── HEADER ─────────────────────────────
    doc.setFontSize(16);
    doc.setFont(undefined, "bold");
    doc.text("BloomBold Resume Review", 14, y);
    y += lineHeight * 2;

    doc.setFontSize(10);
    doc.setFont(undefined, "normal");
    doc.text(
      `Date: ${new Date(review.created_at).toLocaleString()}`,
      14,
      y
    );
    y += lineHeight;

    if (review.target_role) {
      doc.text(`Target Role: ${review.target_role}`, 14, y);
      y += lineHeight * 1.5;
    }

    const results = review.results || {};

    // ─── CONTENT ────────────────────────────
    if (results.overall_impression) {
      sectionTitle("Overall Impression");
      paragraph(results.overall_impression);
    }

    if (results.interview_readiness) {
      sectionTitle("Interview Readiness");
      paragraph(results.interview_readiness);
    }

    if (results.fix_first) {
      sectionTitle("Fix This First");
      paragraph(results.fix_first);
    }

    if (Array.isArray(results.strengths) && results.strengths.length) {
      sectionTitle("Strengths");
      bullets(results.strengths);
    }

    if (Array.isArray(results.gaps) && results.gaps.length) {
      sectionTitle("Gaps to Address");
      bullets(results.gaps);
    }

    if (Array.isArray(results.ats_tips) && results.ats_tips.length) {
      sectionTitle("ATS Tips");
      bullets(results.ats_tips);
    }

    // ─── FOOTER ─────────────────────────────
    ensureSpace(2);
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text("Generated by BloomBold", 14, pageHeight - 15);

    doc.save("bloom-bold-resume-review.pdf");
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <h1 className="text-2xl font-semibold">
        Export Resume Review
      </h1>

      <p className="text-gray-600">
        Download a clean, formatted PDF of your resume feedback.
      </p>

      <button
        onClick={handleExport}
        className="rounded-md bg-black px-6 py-3 text-white font-medium hover:bg-gray-900"
      >
        Download PDF
      </button>
    </div>
  );
}
